library 'cb-sandbox@master'
def testPodYaml = libraryResource 'podtemplates/python/python-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('Python Test and Build')
  {
    stage('Python Tests') {
      agent {
        kubernetes {
          label 'python'
          yaml testPodYaml
       }
      }
      steps {
            checkout scm           
            container('python3') {
              sh '''
                 pipenv install --system
                 '''
            }
      } 
    }
    stage('Build and Push Image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        kanikoBuildPushGeneric("microblog-backend", "latest", "${gcpProject}/${repoOwner}")
        {
          checkout scm
        }
      }
      post {
        success {
          echo "${JOB_NAME} pipeline job is awaiting approval at: ${RUN_DISPLAY_URL}"
        }
      }
    }
    stage("Trigger CD release") {
        agent any
        steps {
            script {
                node() {
                    checkout scm
                    env.VERSION = readFile 'version.txt'
                    env.VERSION = env.VERSION.trim()
                    imageTag = env.VERSION
                    if(env.BRANCH_NAME == 'master'){
                      cloudBeesFlowTriggerRelease configuration: 'SDA-RO', parameters: '{"release":{"releaseName":"The Release","stages":[{"stageName":"Pre-Prod","stageValue":""},{"stageName":"Prod","stageValue":""},{"stageName":"Quality Assurance (QA)","stageValue":""},{"stageName":"Release Readiness","stageValue":""}],"pipelineName":"GA-Fullstack-blog","parameters":[{"parameterName":"FE-Build-number","parameterValue":""},{"parameterName":"BE-Build-number","parameterValue":""},{"parameterName":"microblog-backend_version","parameterValue":"1.0.2"},{"parameterName":"microblog-frontend_version","parameterValue":'+ imageTag +'},{"parameterName":"microblog-db_version","parameterValue":"12.1-alpine"}]}}', projectName: 'Blog', releaseName: 'The Release', startingStage: 'Release Readiness'
                    }
                    if(env.BRANCH_NAME != 'master'){
                      cloudBeesFlowRunPipeline parameters: '{"pipeline":{"pipelineName":"Backend", "parameters":[]}}', projectName: 'Blog', pipelineName: 'Backend', configuration: 'SDA-RO'
                    }

                }
            }
        }
    }
  }
}

